export const DEFAULT_CONTRY_CODE = "+91";
export interface name {
  name: string;
  code: string;
  phoneCode: string;
  flagEmojiEmoji: string;
  [key: string]: any;
}
export const country_codes = [
  // African Countries
  {
    name: "Nigeria",
    population: 232679478,
    flagEmoji: "🇳🇬",
    code: "NG",
    phoneCode: "+234",
  },
  {
    name: "Ethiopia",
    population: 132059767,
    flagEmoji: "🇪🇹",
    code: "ET",
    phoneCode: "+251",
  },
  {
    name: "Egypt",
    population: 116538258,
    flagEmoji: "🇪🇬",
    code: "EG",
    phoneCode: "+20",
  },
  {
    name: "DR Congo",
    population: 109276265,
    flagEmoji: "🇨🇩",
    code: "CD",
    phoneCode: "+243",
  },
  {
    name: "Tanzania",
    population: 68560157,
    flagEmoji: "🇹🇿",
    code: "TZ",
    phoneCode: "+255",
  },
  {
    name: "South Africa",
    population: 64007187,
    flagEmoji: "🇿🇦",
    code: "ZA",
    phoneCode: "+27",
  },
  {
    name: "Kenya",
    population: 56432944,
    flagEmoji: "🇰🇪",
    code: "KE",
    phoneCode: "+254",
  },
  {
    name: "Sudan",
    population: 50448963,
    flagEmoji: "🇸🇩",
    code: "SD",
    phoneCode: "+249",
  },
  {
    name: "Uganda",
    population: 50015092,
    flagEmoji: "🇺🇬",
    code: "UG",
    phoneCode: "+256",
  },
  {
    name: "Algeria",
    population: 46814308,
    flagEmoji: "🇩🇿",
    code: "DZ",
    phoneCode: "+213",
  },
  {
    name: "Morocco",
    population: 38081173,
    flagEmoji: "🇲🇦",
    code: "MA",
    phoneCode: "+212",
  },
  {
    name: "Angola",
    population: 37885849,
    flagEmoji: "🇦🇴",
    code: "AO",
    phoneCode: "+244",
  },
  {
    name: "Mozambique",
    population: 34631766,
    flagEmoji: "🇲🇿",
    code: "MZ",
    phoneCode: "+258",
  },
  {
    name: "Ghana",
    population: 34427414,
    flagEmoji: "🇬🇭",
    code: "GH",
    phoneCode: "+233",
  },
  {
    name: "Madagascar",
    population: 31964956,
    flagEmoji: "🇲🇬",
    code: "MG",
    phoneCode: "+261",
  },
  {
    name: "Côte d'Ivoire",
    population: 31934230,
    flagEmoji: "🇨🇮",
    code: "CI",
    phoneCode: "+225",
  },
  {
    name: "Cameroon",
    population: 29123744,
    flagEmoji: "🇨🇲",
    code: "CM",
    phoneCode: "+237",
  },
  {
    name: "Niger",
    population: 27032412,
    flagEmoji: "🇳🇪",
    code: "NE",
    phoneCode: "+227",
  },
  {
    name: "Mali",
    population: 24478595,
    flagEmoji: "🇲🇱",
    code: "ML",
    phoneCode: "+223",
  },
  {
    name: "Burkina Faso",
    population: 23548781,
    flagEmoji: "🇧🇫",
    code: "BF",
    phoneCode: "+226",
  },
  {
    name: "Malawi",
    population: 21655286,
    flagEmoji: "🇲🇼",
    code: "MW",
    phoneCode: "+265",
  },
  {
    name: "Zambia",
    population: 21314956,
    flagEmoji: "🇿🇲",
    code: "ZM",
    phoneCode: "+260",
  },
  {
    name: "Chad",
    population: 20299123,
    flagEmoji: "🇹🇩",
    code: "TD",
    phoneCode: "+235",
  },
  {
    name: "Somalia",
    population: 19009151,
    flagEmoji: "🇸🇴",
    code: "SO",
    phoneCode: "+252",
  },
  {
    name: "Senegal",
    population: 18501984,
    flagEmoji: "🇸🇳",
    code: "SN",
    phoneCode: "+221",
  },
  {
    name: "Zimbabwe",
    population: 16634373,
    flagEmoji: "🇿🇼",
    code: "ZW",
    phoneCode: "+263",
  },
  {
    name: "Guinea",
    population: 14754785,
    flagEmoji: "🇬🇳",
    code: "GN",
    phoneCode: "+224",
  },
  {
    name: "Benin",
    population: 14462724,
    flagEmoji: "🇧🇯",
    code: "BJ",
    phoneCode: "+229",
  },
  {
    name: "Rwanda",
    population: 14256567,
    flagEmoji: "🇷🇼",
    code: "RW",
    phoneCode: "+250",
  },
  {
    name: "Burundi",
    population: 14047786,
    flagEmoji: "🇧🇮",
    code: "BI",
    phoneCode: "+257",
  },
  {
    name: "Tunisia",
    population: 12277109,
    flagEmoji: "🇹🇳",
    code: "TN",
    phoneCode: "+216",
  },
  {
    name: "South Sudan",
    population: 11943408,
    flagEmoji: "🇸🇸",
    code: "SS",
    phoneCode: "+211",
  },
  {
    name: "Togo",
    population: 9515236,
    flagEmoji: "🇹🇬",
    code: "TG",
    phoneCode: "+228",
  },
  {
    name: "Sierra Leone",
    population: 8642022,
    flagEmoji: "🇸🇱",
    code: "SL",
    phoneCode: "+232",
  },
  {
    name: "Libya",
    population: 7381023,
    flagEmoji: "🇱🇾",
    code: "LY",
    phoneCode: "+218",
  },
  {
    name: "Congo",
    population: 6332961,
    flagEmoji: "🇨🇬",
    code: "CG",
    phoneCode: "+242",
  },
  {
    name: "Liberia",
    population: 5612817,
    flagEmoji: "🇱🇸",
    code: "LR",
    phoneCode: "+231",
  },
  {
    name: "Central African Republic",
    population: 5330690,
    flagEmoji: "🇨🇫",
    code: "CF",
    phoneCode: "+236",
  },
  {
    name: "Mauritania",
    population: 5169395,
    flagEmoji: "🇲🇷",
    code: "MR",
    phoneCode: "+222",
  },
  {
    name: "Eritrea",
    population: 3535603,
    flagEmoji: "🇪🇷",
    code: "ER",
    phoneCode: "+291",
  },
  {
    name: "Namibia",
    population: 3030131,
    flagEmoji: "🇳🇦",
    code: "NA",
    phoneCode: "+264",
  },
  {
    name: "Gambia",
    population: 2759988,
    flagEmoji: "🇬🇲",
    code: "GM",
    phoneCode: "+220",
  },
  {
    name: "Gabon",
    population: 2538952,
    flagEmoji: "🇬🇦",
    code: "GA",
    phoneCode: "+241",
  },
  {
    name: "Botswana",
    population: 2521139,
    flagEmoji: "🇧🇼",
    code: "BW",
    phoneCode: "+267",
  },
  {
    name: "Lesotho",
    population: 2337423,
    flagEmoji: "🇱🇸",
    code: "LS",
    phoneCode: "+266",
  },
  {
    name: "Guinea-Bissau",
    population: 2201352,
    flagEmoji: "🇬🇼",
    code: "GW",
    phoneCode: "+245",
  },
  {
    name: "Equatorial Guinea",
    population: 1892516,
    flagEmoji: "🇬🇶",
    code: "GQ",
    phoneCode: "+240",
  },
  {
    name: "Mauritius",
    population: 1271169,
    flagEmoji: "🇲🇺",
    code: "MU",
    phoneCode: "+230",
  },
  {
    name: "Eswatini",
    population: 1242822,
    flagEmoji: "🇸🇿",
    code: "SZ",
    phoneCode: "+268",
  },
  {
    name: "Djibouti",
    population: 1168722,
    flagEmoji: "🇩🇯",
    code: "DJ",
    phoneCode: "+253",
  },
  {
    name: "Comoros",
    population: 866628,
    flagEmoji: "🇰🇲",
    code: "KM",
    phoneCode: "+269",
  },
  {
    name: "Cabo Verde",
    population: 524877,
    flagEmoji: "🇨🇻",
    code: "CV",
    phoneCode: "+238",
  },
  {
    name: "Sao Tome & Principe",
    population: 235536,
    flagEmoji: "🇸🇹",
    code: "ST",
    phoneCode: "+239",
  },
  {
    name: "Seychelles",
    population: 130418,
    flagEmoji: "🇸🇨",
    code: "SC",
    phoneCode: "+248",
  },

  // Asian Countries
  {
    name: "India",
    population: 1450935791,
    flagEmoji: "🇮🇳",
    code: "IN",
    phoneCode: "+91",
  },
  {
    name: "China",
    population: 1419321278,
    flagEmoji: "🇨🇳",
    code: "CN",
    phoneCode: "+86",
  },
  {
    name: "Indonesia",
    population: 283487931,
    flagEmoji: "🇮🇩",
    code: "ID",
    phoneCode: "+62",
  },
  {
    name: "Pakistan",
    population: 251269164,
    flagEmoji: "🇵🇰",
    code: "PK",
    phoneCode: "+92",
  },
  {
    name: "Bangladesh",
    population: 173562364,
    flagEmoji: "🇧🇩",
    code: "BD",
    phoneCode: "+880",
  },
  {
    name: "Japan",
    population: 123753041,
    flagEmoji: "🇯🇵",
    code: "JP",
    phoneCode: "+81",
  },
  {
    name: "Philippines",
    population: 115843670,
    flagEmoji: "🇵🇭",
    code: "PH",
    phoneCode: "+63",
  },
  {
    name: "Vietnam",
    population: 100987686,
    flagEmoji: "🇻🇳",
    code: "VN",
    phoneCode: "+84",
  },
  {
    name: "Iran",
    population: 91567738,
    flagEmoji: "🇮🇷",
    code: "IR",
    phoneCode: "+98",
  },
  {
    name: "Turkey",
    population: 87473805,
    flagEmoji: "🇹🇷",
    code: "TR",
    phoneCode: "+90",
  },
  {
    name: "Thailand",
    population: 71668011,
    flagEmoji: "🇹🇭",
    code: "TH",
    phoneCode: "+66",
  },
  {
    name: "Myanmar",
    population: 54500091,
    flagEmoji: "🇲🇲",
    code: "MM",
    phoneCode: "+95",
  },
  {
    name: "South Korea",
    population: 51717590,
    flagEmoji: "🇰🇷",
    code: "KR",
    phoneCode: "+82",
  },
  {
    name: "Iraq",
    population: 46042015,
    flagEmoji: "🇮🇶",
    code: "IQ",
    phoneCode: "+964",
  },
  {
    name: "Afghanistan",
    population: 42647492,
    flagEmoji: "🇦🇫",
    code: "AF",
    phoneCode: "+93",
  },
  {
    name: "Yemen",
    population: 40583164,
    flagEmoji: "🇾🇪",
    code: "YE",
    phoneCode: "+967",
  },
  {
    name: "Uzbekistan",
    population: 36361859,
    flagEmoji: "🇺🇿",
    code: "UZ",
    phoneCode: "+998",
  },
  {
    name: "Malaysia",
    population: 35557673,
    flagEmoji: "🇲🇾",
    code: "MY",
    phoneCode: "+60",
  },
  {
    name: "Saudi Arabia",
    population: 33962757,
    flagEmoji: "🇸🇦",
    code: "SA",
    phoneCode: "+966",
  },
  {
    name: "Nepal",
    population: 29651054,
    flagEmoji: "🇳🇵",
    code: "NP",
    phoneCode: "+977",
  },
  {
    name: "North Korea",
    population: 26498823,
    flagEmoji: "🇰🇵",
    code: "KP",
    phoneCode: "+850",
  },
  {
    name: "Syria",
    population: 24672760,
    flagEmoji: "🇸🇾",
    code: "SY",
    phoneCode: "+963",
  },
  {
    name: "Sri Lanka",
    population: 23103565,
    flagEmoji: "🇱🇰",
    code: "LK",
    phoneCode: "+94",
  },
  {
    name: "Kazakhstan",
    population: 20592571,
    flagEmoji: "🇰🇿",
    code: "KZ",
    phoneCode: "+7",
  },
  {
    name: "Cambodia",
    population: 17638801,
    flagEmoji: "🇰🇭",
    code: "KH",
    phoneCode: "+855",
  },
  {
    name: "Jordan",
    population: 11552876,
    flagEmoji: "🇯🇴",
    code: "JO",
    phoneCode: "+962",
  },
  {
    name: "United Arab Emirates",
    population: 11027129,
    flagEmoji: "🇦🇪",
    code: "AE",
    phoneCode: "+971",
  },
  {
    name: "Tajikistan",
    population: 10590927,
    flagEmoji: "🇹🇯",
    code: "TJ",
    phoneCode: "+992",
  },
  {
    name: "Azerbaijan",
    population: 10336577,
    flagEmoji: "🇦🇿",
    code: "AZ",
    phoneCode: "+994",
  },
  {
    name: "Israel",
    population: 9387021,
    flagEmoji: "🇮🇱",
    code: "IL",
    phoneCode: "+972",
  },
  {
    name: "Laos",
    population: 7769819,
    flagEmoji: "🇱🇦",
    code: "LA",
    phoneCode: "+856",
  },
  {
    name: "Turkmenistan",
    population: 7494498,
    flagEmoji: "🇹🇲",
    code: "TM",
    phoneCode: "+993",
  },
  {
    name: "Kyrgyzstan",
    population: 7186009,
    flagEmoji: "🇰🇬",
    code: "KG",
    phoneCode: "+996",
  },
  {
    name: "Singapore",
    population: 5832387,
    flagEmoji: "🇸🇬",
    code: "SG",
    phoneCode: "+65",
  },
  {
    name: "Lebanon",
    population: 5805962,
    flagEmoji: "🇱🇧",
    code: "LB",
    phoneCode: "+961",
  },
  {
    name: "State of Palestine",
    population: 5495443,
    flagEmoji: "🇵🇸",
    code: "PS",
    phoneCode: "+970",
  },
  {
    name: "Oman",
    population: 5281538,
    flagEmoji: "🇴🇲",
    code: "OM",
    phoneCode: "+968",
  },
  {
    name: "Kuwait",
    population: 4934507,
    flagEmoji: "🇰🇼",
    code: "KW",
    phoneCode: "+965",
  },
  {
    name: "Georgia",
    population: 3807670,
    flagEmoji: "🇬🇪",
    code: "GE",
    phoneCode: "+995",
  },
  {
    name: "Mongolia",
    population: 3475540,
    flagEmoji: "🇲🇳",
    code: "MN",
    phoneCode: "+976",
  },
  {
    name: "Qatar",
    population: 3048423,
    flagEmoji: "🇶🇦",
    code: "QA",
    phoneCode: "+974",
  },
  {
    name: "Armenia",
    population: 2973840,
    flagEmoji: "🇦🇲",
    code: "AM",
    phoneCode: "+374",
  },
  {
    name: "Bahrain",
    population: 1607049,
    flagEmoji: "🇧🇭",
    code: "BH",
    phoneCode: "+973",
  },
  {
    name: "Timor-Leste",
    population: 1400638,
    flagEmoji: "🇹🇱",
    code: "TL",
    phoneCode: "+670",
  },
  {
    name: "Cyprus",
    population: 1358282,
    flagEmoji: "🇨🇾",
    code: "CY",
    phoneCode: "+357",
  },
  {
    name: "Bhutan",
    population: 791524,
    flagEmoji: "🇧🇹",
    code: "BT",
    phoneCode: "+975",
  },
  {
    name: "Maldives",
    population: 527799,
    flagEmoji: "🇲🇻",
    code: "MV",
    phoneCode: "+960",
  },
  {
    name: "Brunei",
    population: 462721,
    flagEmoji: "🇧🇳",
    code: "BN",
    phoneCode: "+673",
  },

  // Countries in Europe:

  {
    name: "Russia",
    population: 144820423,
    flagEmoji: "🇷🇺",
    code: "RU",
    phoneCode: "+7",
  },
  {
    name: "Germany",
    population: 84552242,
    flagEmoji: "🇩🇪",
    code: "DE",
    phoneCode: "+49",
  },
  {
    name: "United Kingdom",
    population: 69138192,
    flagEmoji: "🇬🇧",
    code: "GB",
    phoneCode: "+44",
  },
  {
    name: "France",
    population: 66548530,
    flagEmoji: "🇫🇷",
    code: "FR",
    phoneCode: "+33",
  },
  {
    name: "Italy",
    population: 59342867,
    flagEmoji: "🇮🇹",
    code: "IT",
    phoneCode: "+39",
  },
  {
    name: "Spain",
    population: 47910526,
    flagEmoji: "🇪🇸",
    code: "ES",
    phoneCode: "+34",
  },
  {
    name: "Poland",
    population: 38539201,
    flagEmoji: "🇵🇱",
    code: "PL",
    phoneCode: "+48",
  },
  {
    name: "Ukraine",
    population: 37860221,
    flagEmoji: "🇺🇦",
    code: "UA",
    phoneCode: "+380",
  },
  {
    name: "Romania",
    population: 19015088,
    flagEmoji: "🇷🇴",
    code: "RO",
    phoneCode: "+40",
  },
  {
    name: "Netherlands",
    population: 18228742,
    flagEmoji: "🇳🇱",
    code: "NL",
    phoneCode: "+31",
  },
  {
    name: "Belgium",
    population: 11738763,
    flagEmoji: "🇧🇪",
    code: "BE",
    phoneCode: "+32",
  },
  {
    name: "Czech Republic (Czechia)",
    population: 10735859,
    flagEmoji: "🇨🇿",
    code: "CZ",
    phoneCode: "+420",
  },
  {
    name: "Sweden",
    population: 10606999,
    flagEmoji: "🇸🇪",
    code: "SE",
    phoneCode: "+46",
  },
  {
    name: "Portugal",
    population: 10425292,
    flagEmoji: "🇵🇹",
    code: "PT",
    phoneCode: "+351",
  },
  {
    name: "Greece",
    population: 10047817,
    flagEmoji: "🇬🇷",
    code: "GR",
    phoneCode: "+30",
  },
  {
    name: "Hungary",
    population: 9676135,
    flagEmoji: "🇭🇺",
    code: "HU",
    phoneCode: "+36",
  },
  {
    name: "Austria",
    population: 9120813,
    flagEmoji: "🇦🇹",
    code: "AT",
    phoneCode: "+43",
  },
  {
    name: "Belarus",
    population: 9056696,
    flagEmoji: "🇧🇾",
    code: "BY",
    phoneCode: "+375",
  },
  {
    name: "Switzerland",
    population: 8921981,
    flagEmoji: "🇨🇭",
    code: "CH",
    phoneCode: "+41",
  },
  {
    name: "Bulgaria",
    population: 6757689,
    flagEmoji: "🇧🇬",
    code: "BG",
    phoneCode: "+359",
  },
  {
    name: "Serbia",
    population: 6736216,
    flagEmoji: "🇷🇸",
    code: "RS",
    phoneCode: "+381",
  },
  {
    name: "Denmark",
    population: 5977412,
    flagEmoji: "🇩🇰",
    code: "DK",
    phoneCode: "+45",
  },
  {
    name: "Finland",
    population: 5617310,
    flagEmoji: "🇫🇮",
    code: "FI",
    phoneCode: "+358",
  },
  {
    name: "Norway",
    population: 5576660,
    flagEmoji: "🇳🇴",
    code: "NO",
    phoneCode: "+47",
  },
  {
    name: "Slovakia",
    population: 5506760,
    flagEmoji: "🇸🇰",
    code: "SK",
    phoneCode: "+421",
  },
  {
    name: "Ireland",
    population: 5255017,
    flagEmoji: "🇮🇪",
    code: "IE",
    phoneCode: "+353",
  },
  {
    name: "Croatia",
    population: 3875325,
    flagEmoji: "🇭🇷",
    code: "HR",
    phoneCode: "+385",
  },
  {
    name: "Bosnia and Herzegovina",
    population: 3164253,
    flagEmoji: "🇧🇦",
    code: "BA",
    phoneCode: "+387",
  },
  {
    name: "Moldova",
    population: 3034961,
    flagEmoji: "🇲🇩",
    code: "MD",
    phoneCode: "+373",
  },
  {
    name: "Lithuania",
    population: 2859110,
    flagEmoji: "🇱🇹",
    code: "LT",
    phoneCode: "+370",
  },
  {
    name: "Albania",
    population: 2791765,
    flagEmoji: "🇦🇱",
    code: "AL",
    phoneCode: "+355",
  },
  {
    name: "Slovenia",
    population: 2118697,
    flagEmoji: "🇸🇮",
    code: "SI",
    phoneCode: "+386",
  },
  {
    name: "Latvia",
    population: 1871871,
    flagEmoji: "🇱🇻",
    code: "LV",
    phoneCode: "+371",
  },
  {
    name: "North Macedonia",
    population: 1823009,
    flagEmoji: "🇲🇰",
    code: "MK",
    phoneCode: "+389",
  },
  {
    name: "Estonia",
    population: 1360546,
    flagEmoji: "🇪🇪",
    code: "EE",
    phoneCode: "+372",
  },
  {
    name: "Luxembourg",
    population: 673036,
    flagEmoji: "🇱🇺",
    code: "LU",
    phoneCode: "+352",
  },
  {
    name: "Montenegro",
    population: 638479,
    flagEmoji: "🇲🇪",
    code: "ME",
    phoneCode: "+382",
  },
  {
    name: "Malta",
    population: 539607,
    flagEmoji: "🇲🇹",
    code: "MT",
    phoneCode: "+356",
  },
  {
    name: "Iceland",
    population: 393396,
    flagEmoji: "🇮🇸",
    code: "IS",
    phoneCode: "+354",
  },
  {
    name: "Andorra",
    population: 81938,
    flagEmoji: "🇦🇩",
    code: "AD",
    phoneCode: "+376",
  },
  {
    name: "Liechtenstein",
    population: 39870,
    flagEmoji: "🇱🇮",
    code: "LI",
    phoneCode: "+423",
  },
  {
    name: "Monaco",
    population: 38631,
    flagEmoji: "🇲🇨",
    code: "MC",
    phoneCode: "+377",
  },
  {
    name: "San Marino",
    population: 33581,
    flagEmoji: "🇸🇲",
    code: "SM",
    phoneCode: "+378",
  },
  {
    name: "Holy See",
    population: 496,
    flagEmoji: "🇻🇦",
    code: "VA",
    phoneCode: "+379",
  },

  {
    name: "Taiwan",
    population: 23213962,
    flagEmoji: "🇹🇼",
    code: "TW",
    phoneCode: "+886",
  },
  {
    name: "Hong Kong",
    population: 7414909,
    flagEmoji: "🇭🇰",
    code: "HK",
    phoneCode: "+852",
  },
  {
    name: "Macao",
    population: 720262,
    flagEmoji: "🇲🇴",
    code: "MO",
    phoneCode: "+853",
  },

  {
    name: "Réunion",
    population: 878591,
    flagEmoji: "🇷🇪",
    code: "RE",
    phoneCode: "+262",
  },
  {
    name: "Western Sahara",
    population: 590506,
    flagEmoji: "🇪🇭",
    code: "EH",
    phoneCode: "+212",
  },
  {
    name: "Mayotte",
    population: 326505,
    flagEmoji: "🇾🇹",
    code: "YT",
    phoneCode: "+262",
  },
  {
    name: "Saint Helena",
    population: 5237,
    flagEmoji: "🇸🇭",
    code: "SH",
    phoneCode: "+290",
  },

  // Countries in Latin America and the Caribbean:

  {
    name: "Brazil",
    population: 211998573,
    flagEmoji: "🇧🇷",
    code: "BR",
    phoneCode: "+55",
  },
  {
    name: "Mexico",
    population: 130861007,
    flagEmoji: "🇲🇽",
    code: "MX",
    phoneCode: "+52",
  },
  {
    name: "Colombia",
    population: 52886363,
    flagEmoji: "🇨🇴",
    code: "CO",
    phoneCode: "+57",
  },
  {
    name: "Argentina",
    population: 45696159,
    flagEmoji: "🇦🇷",
    code: "AR",
    phoneCode: "+54",
  },
  {
    name: "Peru",
    population: 34217848,
    flagEmoji: "🇵🇪",
    code: "PE",
    phoneCode: "+51",
  },
  {
    name: "Venezuela",
    population: 28405543,
    flagEmoji: "🇻🇪",
    code: "VE",
    phoneCode: "+58",
  },
  {
    name: "Chile",
    population: 19764771,
    flagEmoji: "🇨🇱",
    code: "CL",
    phoneCode: "+56",
  },
  {
    name: "Guatemala",
    population: 18406359,
    flagEmoji: "🇬🇹",
    code: "GT",
    phoneCode: "+502",
  },
  {
    name: "Ecuador",
    population: 18135478,
    flagEmoji: "🇪🇨",
    code: "EC",
    phoneCode: "+593",
  },
  {
    name: "Bolivia",
    population: 12413315,
    flagEmoji: "🇧🇴",
    code: "BO",
    phoneCode: "+591",
  },
  {
    name: "Haiti",
    population: 11772557,
    flagEmoji: "🇭🇹",
    code: "HT",
    phoneCode: "+509",
  },
  {
    name: "Dominican Republic",
    population: 11427557,
    flagEmoji: "🇩🇴",
    code: "DO",
    phoneCode: "+1-809",
  },
  {
    name: "Cuba",
    population: 10979783,
    flagEmoji: "🇨🇺",
    code: "CU",
    phoneCode: "+53",
  },
  {
    name: "Honduras",
    population: 10825703,
    flagEmoji: "🇭🇳",
    code: "HN",
    phoneCode: "+504",
  },
  {
    name: "Paraguay",
    population: 6929153,
    flagEmoji: "🇵🇾",
    code: "PY",
    phoneCode: "+595",
  },
  {
    name: "Nicaragua",
    population: 6916140,
    flagEmoji: "🇳🇮",
    code: "NI",
    phoneCode: "+505",
  },
  {
    name: "El Salvador",
    population: 6338193,
    flagEmoji: "🇸🇻",
    code: "SV",
    phoneCode: "+503",
  },
  {
    name: "Costa Rica",
    population: 5129910,
    flagEmoji: "🇨🇷",
    code: "CR",
    phoneCode: "+506",
  },
  {
    name: "Panama",
    population: 4515577,
    flagEmoji: "🇵🇦",
    code: "PA",
    phoneCode: "+507",
  },
  {
    name: "Uruguay",
    population: 3386588,
    flagEmoji: "🇺🇾",
    code: "UY",
    phoneCode: "+598",
  },
  {
    name: "Jamaica",
    population: 2839175,
    flagEmoji: "🇯🇲",
    code: "JM",
    phoneCode: "+1-876",
  },
  {
    name: "Trinidad and Tobago",
    population: 1507782,
    flagEmoji: "🇹🇹",
    code: "TT",
    phoneCode: "+1-868",
  },
  {
    name: "Guyana",
    population: 831087,
    flagEmoji: "🇬🇾",
    code: "GY",
    phoneCode: "+592",
  },
  {
    name: "Suriname",
    population: 634431,
    flagEmoji: "🇸🇷",
    code: "SR",
    phoneCode: "+597",
  },
  {
    name: "Belize",
    population: 417072,
    flagEmoji: "🇧🇿",
    code: "BZ",
    phoneCode: "+501",
  },
  {
    name: "Bahamas",
    population: 401283,
    flagEmoji: "🇧🇸",
    code: "BS",
    phoneCode: "+1-242",
  },
  {
    name: "Barbados",
    population: 282467,
    flagEmoji: "🇧🇧",
    code: "BB",
    phoneCode: "+1-246",
  },
  {
    name: "Saint Lucia",
    population: 179744,
    flagEmoji: "🇱🇨",
    code: "LC",
    phoneCode: "+1-758",
  },
  {
    name: "Grenada",
    population: 117207,
    flagEmoji: "🇬🇩",
    code: "GD",
    phoneCode: "+1-473",
  },
  {
    name: "St. Vincent & Grenadines",
    population: 100616,
    flagEmoji: "🇻🇨",
    code: "VC",
    phoneCode: "+1-784",
  },
  {
    name: "Antigua and Barbuda",
    population: 93772,
    flagEmoji: "🇦🇬",
    code: "AG",
    phoneCode: "+1-268",
  },
  {
    name: "Dominica",
    population: 66205,
    flagEmoji: "🇩🇲",
    code: "DM",
    phoneCode: "+1-767",
  },
  {
    name: "Saint Kitts & Nevis",
    population: 46843,
    flagEmoji: "🇰🇳",
    code: "KN",
    phoneCode: "+1-869",
  },

  // Countries in Latin America and the Caribbean: Dependencies or other territories:

  {
    name: "Isle of Man",
    population: 84160,
    flagEmoji: "🇮🇲",
    code: "IM",
    phoneCode: "+44",
  },
  {
    name: "Faeroe Islands",
    population: 55400,
    flagEmoji: "🇫🇴",
    code: "FO",
    phoneCode: "+298",
  },
  {
    name: "Gibraltar",
    population: 39329,
    flagEmoji: "🇬🇮",
    code: "GI",
    phoneCode: "+350",
  },

  // Countries in Latin America and the Caribbean:  Dependencies or other territories:

  {
    name: "Puerto Rico",
    population: 3242204,
    flagEmoji: "🇵🇷",
    code: "PR",
    phoneCode: "+1-787, +1-939",
  },
  {
    name: "Guadeloupe",
    population: 375106,
    flagEmoji: "🇬🇩",
    code: "GP",
    phoneCode: "+590",
  },
  {
    name: "Martinique",
    population: 343195,
    flagEmoji: "🇲🇶",
    code: "MQ",
    phoneCode: "+596",
  },
  {
    name: "French Guiana",
    population: 308522,
    flagEmoji: "🇬🇫",
    code: "GF",
    phoneCode: "+594",
  },
  {
    name: "Curaçao",
    population: 185482,
    flagEmoji: "🇨🇼",
    code: "CW",
    phoneCode: "+599",
  },
  {
    name: "Aruba",
    population: 108066,
    flagEmoji: "🇦🇼",
    code: "AW",
    phoneCode: "+297",
  },
  {
    name: "U.S. Virgin Islands",
    population: 84905,
    flagEmoji: "🇻🇮",
    code: "VI",
    phoneCode: "+1-340",
  },
  {
    name: "Cayman Islands",
    population: 74457,
    flagEmoji: "🇰🇾",
    code: "KY",
    phoneCode: "+1-345",
  },
  {
    name: "Turks and Caicos Islands",
    population: 46535,
    flagEmoji: "🇹🇨",
    code: "TC",
    phoneCode: "+1-649",
  },
  {
    name: "Sint Maarten",
    population: 43350,
    flagEmoji: "🇸🇽",
    code: "SX",
    phoneCode: "+1-721",
  },
  {
    name: "British Virgin Islands",
    population: 39471,
    flagEmoji: "🇻🇬",
    code: "VG",
    phoneCode: "+1-284",
  },
  {
    name: "Caribbean Netherlands",
    population: 30675,
    flagEmoji: "🇧🇶",
    code: "BQ",
    phoneCode: "+599",
  },
  {
    name: "Anguilla",
    population: 14598,
    flagEmoji: "🇦🇮",
    code: "AI",
    phoneCode: "+1-264",
  },
  {
    name: "Montserrat",
    population: 4389,
    flagEmoji: "🇲🇸",
    code: "MS",
    phoneCode: "+1-664",
  },
  {
    name: "Falkland Islands",
    population: 3470,
    flagEmoji: "🇫🇰",
    code: "FK",
    phoneCode: "+500",
  },

  // Countries in Oceania:

  {
    name: "Australia",
    population: 26713205,
    flagEmoji: "🇦🇺",
    code: "AU",
    phoneCode: "+61",
  },
  {
    name: "Papua New Guinea",
    population: 10576502,
    flagEmoji: "🇵🇬",
    code: "PG",
    phoneCode: "+675",
  },
  {
    name: "New Zealand",
    population: 5213944,
    flagEmoji: "🇳🇿",
    code: "NZ",
    phoneCode: "+64",
  },
  {
    name: "Fiji",
    population: 928784,
    flagEmoji: "🇫🇯",
    code: "FJ",
    phoneCode: "+679",
  },
  {
    name: "Solomon Islands",
    population: 819198,
    flagEmoji: "🇸🇧",
    code: "SB",
    phoneCode: "+677",
  },
  {
    name: "Micronesia",
    population: 526923,
    flagEmoji: "🇫🇲",
    code: "FM",
    phoneCode: "+691",
  },
  {
    name: "Vanuatu",
    population: 327777,
    flagEmoji: "🇻🇺",
    code: "VU",
    phoneCode: "+678",
  },
  {
    name: "Samoa",
    population: 218019,
    flagEmoji: "🇼🇸",
    code: "WS",
    phoneCode: "+685",
  },
  {
    name: "Kiribati",
    population: 134518,
    flagEmoji: "🇰🇮",
    code: "KI",
    phoneCode: "+686",
  },
  {
    name: "Tonga",
    population: 104175,
    flagEmoji: "🇹🇴",
    code: "TO",
    phoneCode: "+676",
  },
  {
    name: "Marshall Islands",
    population: 37548,
    flagEmoji: "🇲🇭",
    code: "MH",
    phoneCode: "+692",
  },
  {
    name: "Palau",
    population: 17695,
    flagEmoji: "🇵🇼",
    code: "PW",
    phoneCode: "+680",
  },
  {
    name: "Nauru",
    population: 11947,
    flagEmoji: "🇳🇷",
    code: "NR",
    phoneCode: "+674",
  },
  {
    name: "Tuvalu",
    population: 9646,
    flagEmoji: "🇹🇻",
    code: "TV",
    phoneCode: "+688",
  },

  // Countries in Oceania: Dependencies or other territories

  {
    name: "New Caledonia",
    population: 292639,
    flagEmoji: "🇳🇨",
    code: "NC",
    phoneCode: "+687",
  },
  {
    name: "French Polynesia",
    population: 281807,
    flagEmoji: "🇵🇫",
    code: "PF",
    phoneCode: "+689",
  },
  {
    name: "Guam",
    population: 167777,
    flagEmoji: "🇬🇺",
    code: "GU",
    phoneCode: "+1-671",
  },
  {
    name: "American Samoa",
    population: 46765,
    flagEmoji: "🇦🇸",
    code: "AS",
    phoneCode: "+1-684",
  },
  {
    name: "Northern Mariana Islands",
    population: 44278,
    flagEmoji: "🇲🇵",
    code: "MP",
    phoneCode: "+1-670",
  },
  {
    name: "Cook Islands",
    population: 13729,
    flagEmoji: "🇨🇰",
    code: "CK",
    phoneCode: "+682",
  },
  {
    name: "Wallis & Futuna",
    population: 11277,
    flagEmoji: "🇼🇫",
    code: "WF",
    phoneCode: "+681",
  },
  {
    name: "Tokelau",
    population: 2506,
    flagEmoji: "🇹🇰",
    code: "TK",
    phoneCode: "+690",
  },
  {
    name: "Niue",
    population: 1819,
    flagEmoji: "🇳🇺",
    code: "NU",
    phoneCode: "+683",
  },

  // Countries in Northern America:

  {
    name: "United States",
    population: 345426571,
    flagEmoji: "🇺🇸",
    code: "US",
    phoneCode: "+1",
  },
  {
    name: "Canada",
    population: 39742430,
    flagEmoji: "🇨🇦",
    code: "CA",
    phoneCode: "+1",
  },

  // Countries in Northern America: Dependencies or other territories

  {
    name: "Bermuda",
    population: 64636,
    flagEmoji: "🇧🇲",
    code: "BM",
    phoneCode: "+1-441",
  },
  {
    name: "Greenland",
    population: 55840,
    flagEmoji: "🇬🇱",
    code: "GL",
    phoneCode: "+299",
  },
  {
    name: "Saint Pierre & Miquelon",
    population: 5628,
    flagEmoji: "🇵🇲",
    code: "PM",
    phoneCode: "+508",
  },
].sort((a, b) => a.name.localeCompare(b.name));
