export const COLLECTIONS = {
  users: "users_infos",
  projects: "projects",
  fundraisers: "fundraisers",
  donations: "donations",
  donor: "donor",
  update: "update",
  newsletter: "newsletter",
  un_subscrive: "un_subscrive",
  contact_us: "contact_us",
  stripe_payment_copy: "stripe_payment_copy",
  donations_copy: "donations_copy",
  currency_rates: "currency_rates",
  razore_pay_payment_copy: "razore_pay_payment_copy",
  razore_subscription_copy: "razore_subscription_copy",
  verix_copy: "verix_copy",
  crons_jobs: "crons_jobs",
  csv_projectreate_test: "csv_projectreate_test",
  verix_images: "verix_images",
  user_badges: "user_badges",
  wordPress_published_posts_copy: "wordPress_published_posts_copy",
  wordPress_deleted_posts_copy: "wordPress_deleted_posts_copy",
  ambassadors: "ambassadors",
  auth_otps: "auth_otps",
  auth_rate_limits: "auth_rate_limits",
  auth_audit_logs: "auth_audit_logs",
  runtime_errors: "runtime_errors",
  adminCredentials: "admin_credentials",
  adminSavedFiles: "admin_saved_files",
  cron_locks: "cron_locks",

  // Agent-specific collections (unique to cpw-agent)
  agent_conversations: "agentconversations",
  agent_feedback: "agent_feedback",
  agent_logs: "agent_logs",
} as const;
